//
// Created by kobia on 05.03.2023.
//

#ifndef MYLANGUAGE_TOKENTYPE_H
#define MYLANGUAGE_TOKENTYPE_H


enum TokenType {
    NUMBER, HEX_NUMBER, PLUS, MINUS, STAR, SLASH, EOL, LPAREN, RPAREN, WHILE, FOR, ELSE, IF
};


#endif //MYLANGUAGE_TOKENTYPE_H
